on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: check files
        run: ls -a
      - name: yarn install
        run: yarn
      - name: check files
        run: ls -a
      - name: custom_workflow_step
        uses: K-Sato1995/gh-actions-test@v2.8
        with:
          name: 'custom name'
          message: "Message"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
